version: '3.9'

services:
  bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/bot
    networks:
      - test-mission_default
    ports:
     - "2222:2222"

networks:
  test-mission_default:
    external: true
